SRTM2Wayinfo: SrtmDownloader Class Reference
SrtmDownloader Class Reference
Downloads SRTM data from NASA's server.
#include <srtm.h>
Public Member Functions
SrtmDownloader (QString url, QString cachedir)
Constructor for SrtmDownloader.
void createFileList ()
Create a new file list by getting directory contents from server.
void loadFileList ()
Load a file list or create a new one if it doesn't exist.
SrtmTile * getTile (float lat, float lon)
Get tile for a specified location.
void downloadTile (QString filename)
Download a tile from the server.
float getAltitudeFromLatLon (float lat, float lon)
Get altitude and download necessary tiles automatically.
void curlAddData (void *ptr, int size)
One line helper function.
Detailed Description
Downloads SRTM data from NASA's server.
Definition at line 61 of file srtm.h.
Constructor & Destructor Documentation
SrtmDownloader::SrtmDownloader (QString url, QString cachedir)
Constructor for SrtmDownloader.
Note:
This downloader currently only supports SRTM3 data.
Parameters:
url URL to the SRTM data.
cachedir Directory in which the downloaded files are stored.
Definition at line 52 of file srtm.cpp.
References loadFileList().
Member Function Documentation
void SrtmDownloader::createFileList ()
Create a new file list by getting directory contents from server.
Definition at line 74 of file srtm.cpp.
References curl_data_callback(), and SRTM_FILE_COUNT.
Referenced by loadFileList().
void SrtmDownloader::curlAddData (void * ptr, int size)
One line helper function.
Definition at line 68 of file srtm.cpp.
Referenced by curl_data_callback().
void SrtmDownloader::downloadTile (QString filename)
Download a tile from the server.
Parameters:
filename must be in the format continent/tilename.hgt.zip
Note:
You should _not_ call this function when you need tile data. Use getTile instead.
Definition at line 169 of file srtm.cpp.
References curl_file_callback().
Referenced by getTile().
float SrtmDownloader::getAltitudeFromLatLon (float lat, float lon)
Get altitude and download necessary tiles automatically.
Definition at line 191 of file srtm.cpp.
References SrtmTile::getAltitudeFromLatLon(), getTile(), and SRTM_DATA_VOID.
SrtmTile * SrtmDownloader::getTile (float lat, float lon)
Get tile for a specified location.
Note:
The tile object returned is owned by this SrtmDownloader instance. It _must_ _not_ be deleted by the user. However it _may_ be deleted by SrtmDownloader during any later call to getTile()
Definition at line 144 of file srtm.cpp.
References downloadTile(), and errorTile.
Referenced by getAltitudeFromLatLon().
void SrtmDownloader::loadFileList ()
Load a file list or create a new one if it doesn't exist.
Definition at line 124 of file srtm.cpp.
References createFileList(), and SRTM_FILE_COUNT.
Referenced by SrtmDownloader().
The documentation for this class was generated from the following files:
srtm.h
srtm.cpp