SRTM2Wayinfo: OsmNode Class Reference
OsmNode Class Reference
Stores information about an OSM node.
#include <osmtypes.h>
Public Member Functions
OsmNode ()
Default constructor.
OsmNode (float lat, float lon)
Constructor with initialisation.
float lat ()
Return latitude value.
float lon ()
Return longitude value.
void incOrder ()
Increase order of this node.
bool isIntersection ()
Check if a node is an intersection.
Detailed Description
Stores information about an OSM node.
Most functions should be defined in the header so the can be inlined because they will be called very often. This class should be optimized for storage size and can store different values together. All data is accessed via functions to allow unpacking of data.
We only want to know if a node is a junction. Therefore we can stop counting at order 2. Data about the order is stored in the lat value. Normal lat values: -90° to +90° (+ 0°) 1st order node: 110° to 290° (+200°) 2nd order node: 310° to 490° (+400°) I choose 200° instead of 180° to avoid corner cases and because the values are easier to read for a human.
Definition at line 42 of file osmtypes.h.
Constructor & Destructor Documentation
OsmNode::OsmNode () [inline]
Default constructor.
Creates an invalid node.
Note:
This function is required for QList<OsmNode>.
Definition at line 49 of file osmtypes.h.
OsmNode::OsmNode (float lat, float lon) [inline]
Constructor with initialisation.
Definition at line 52 of file osmtypes.h.
References lat(), and lon().
Member Function Documentation
void OsmNode::incOrder () [inline]
Increase order of this node.
Note:
The counter is only required to count up to order 2, but is allowed to count up to any value.
Definition at line 75 of file osmtypes.h.
bool OsmNode::isIntersection () [inline]
Check if a node is an intersection.
Definition at line 80 of file osmtypes.h.
float OsmNode::lat () [inline]
Return latitude value.
Definition at line 59 of file osmtypes.h.
Referenced by OsmNode().
float OsmNode::lon () [inline]
Return longitude value.
Definition at line 70 of file osmtypes.h.
Referenced by OsmNode().
The documentation for this class was generated from the following file:
osmtypes.h