SRTM2Wayinfo: srtm.cpp File Reference
srtm.cpp File Reference
SRTM data downloader and tile handler.
#include "srtm.h"
#include "zip.h"
#include <math.h>
#include <QDir>
#include <QStringList>
#include <QString>
#include <QProcess>
#include <QDebug>
#include <qendian.h>
Functions
size_t curl_data_callback (void *ptr, size_t size, size_t nmemb, void *stream)
Callback from curl for data that is not stored in a file but kept in memory.
size_t curl_file_callback (char *ptr, size_t size, size_t nmemb, void *stream)
Callback from curl for data that is stored in a file.
Variables
SrtmTile errorTile ("error",-1000,-1000)
Standard error tile that is returned when something goes wrong.
Detailed Description
SRTM data downloader and tile handler.
Definition in file srtm.cpp.
Function Documentation
size_t curl_data_callback (void * ptr, size_t size, size_t nmemb, void * stream)
Callback from curl for data that is not stored in a file but kept in memory.
Definition at line 23 of file srtm.cpp.
References SrtmDownloader::curlAddData().
Referenced by SrtmDownloader::createFileList().
size_t curl_file_callback (char * ptr, size_t size, size_t nmemb, void * stream)
Callback from curl for data that is stored in a file.
Definition at line 31 of file srtm.cpp.
Referenced by SrtmDownloader::downloadTile().
Variable Documentation
SrtmTile errorTile("error",-1000,-1000)
Standard error tile that is returned when something goes wrong.
Referenced by SrtmDownloader::getTile().