SRTM2Wayinfo: OsmData Class Reference
OsmData Class Reference
Parses and stores all (relevant) information contained in an OSM file.
#include <osm-parse.h>
Public Member Functions
OsmData (OsmWayStorage *ways, OsmNodeStorage *nodes)
void parse (QString filename)
Parse an OSM-XML file.
void parse (QFile *file)
Parse an OSM-XML file.
Public Attributes
OsmNodeStorage * nodes
Maps all node IDs for to their node objects.
OsmWayStorage * ways
List of all way objects.
Protected Member Functions
void processTag (char *tag)
void processParam (char *tag, char *name, char *value)
Protected Attributes
OsmWay currentWay
QStringList wayTags
OsmNodeId nodeid
OsmNodeId noderef
OsmWayId wayid
float lat
float lon
bool keep
Detailed Description
Parses and stores all (relevant) information contained in an OSM file.
Definition at line 22 of file osm-parse.h.
Member Function Documentation
void OsmData::parse (QString filename)
Parse an OSM-XML file.
This function is just a wrapper that creates an QFile object and calls parse(QFile *).
Definition at line 22 of file osm-parse-old.cpp.
Referenced by main().
void OsmData::parse (QFile * file)
Parse an OSM-XML file.
Stores information about the parsed data in the "nodes" and "ways" arrays.
Stores information about the parsed data in the "nodes" and "ways" arrays.
Note:
This parser doesn't fail when the input data is invalid. It goes on reading and produces unpredictable results. However there should be no possiblity of a buffer overrun.
Definition at line 33 of file osm-parse-old.cpp.
References OsmWay::addNode(), OsmWay::clear(), OsmWay::nodes, OsmWay::setId(), and ways.
Member Data Documentation
OsmNodeStorage* OsmData::nodes
Maps all node IDs for to their node objects.
Definition at line 33 of file osm-parse.h.
OsmWayStorage* OsmData::ways
List of all way objects.
Definition at line 35 of file osm-parse.h.
Referenced by parse(), and RelationWriter::writeRelations().
The documentation for this class was generated from the following files:
osm-parse.h
osm-parse-old.cpp
osm-parse.cpp