SRTM2Wayinfo: Settings Class Reference
Settings Class Reference
Stores all settings.
#include <settings.h>
Public Member Functions
void parseSettings (int argc, char **argv)
Parses the command line and fills the settings structure.
const char * getInput () const
Get input file.
const char * getOutput () const
Get output file.
const char * getSrtmServer () const
Get URL of SRTM server.
const char * getCacheDir () const
Get cache dir.
bool getStoreUncompressed () const
Should the uncompressed data also be stored on disk?
void usage ()
Show usage instructions.
dataset_size getDatasetSize () const
For which input data size should the node and way storage be optimized?
Detailed Description
Stores all settings.
Definition at line 19 of file settings.h.
Member Function Documentation
const char* Settings::getCacheDir () const [inline]
Get cache dir.
Definition at line 55 of file settings.h.
Referenced by main().
const char* Settings::getInput () const [inline]
Get input file.
If none is given read from stdin.
Definition at line 35 of file settings.h.
Referenced by main().
const char* Settings::getOutput () const [inline]
Get output file.
If none is given write to stdout.
Definition at line 43 of file settings.h.
Referenced by main().
const char* Settings::getSrtmServer () const [inline]
Get URL of SRTM server.
Definition at line 49 of file settings.h.
Referenced by main().
void Settings::parseSettings (int argc, char ** argv)
Parses the command line and fills the settings structure.
This function uses the getopt functions provided by glibc and has GNU style option handling.
Definition at line 46 of file settings.cpp.
References usage().
Referenced by main().
void Settings::usage ()
Show usage instructions.
Definition at line 16 of file settings.cpp.
Referenced by parseSettings().
The documentation for this class was generated from the following files:
settings.h
settings.cpp