SRTM2Wayinfo: SrtmTile Class Reference
SrtmTile Class Reference
Handles the loading and parsing of an SRTM tile.
#include <srtm.h>
Public Member Functions
SrtmTile (QString file, int lat, int lon)
Create a new tile object.
~SrtmTile ()
Free resources.
int getPixelValue (int x, int y)
Get the value of a pixel from the data using a coordinate system starting in the upper left (NW) edge growing to the lower right egde (SE) instead of the SRTM coordinate system.
float getAltitudeFromLatLon (float lat, float lon)
Gets the altitude in meters for a given coordinate.
Detailed Description
Handles the loading and parsing of an SRTM tile.
This class should work for both SRTM1 and SRTM3 data. But currently only SRTM3 is used.
Definition at line 29 of file srtm.h.
Constructor & Destructor Documentation
SrtmTile::SrtmTile (QString filename, int lat, int lon)
Create a new tile object.
Unzips the tile data if necessary.
Note:
Special filename: "error" returns an invalid tile.
Definition at line 203 of file srtm.cpp.
References SrtmZipFile::getData().
SrtmTile::~SrtmTile ()
Free resources.
Definition at line 217 of file srtm.cpp.
Member Function Documentation
float SrtmTile::getAltitudeFromLatLon (float lat, float lon)
Gets the altitude in meters for a given coordinate.
Definition at line 236 of file srtm.cpp.
References getPixelValue(), and SRTM_DATA_VOID.
Referenced by SrtmDownloader::getAltitudeFromLatLon().
The documentation for this class was generated from the following files:
srtm.h
srtm.cpp